language: python
dist: trusty
sudo: false

python:
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3.5-5.8.0"

cache: pip

script:
   - python setup.py develop
   - pip3 install pytest-httpbin
   - pip3 install git+https://github.com/python-trio/trio.git
   - pip3 install git+https://github.com/dabeaz/curio.git
   - pip3 install pylint

